# LAB 01 - NumPy Library [1]

## #02. `ndarray` 주요 기능

### 라이브러리 참조하기

In [1]:
import numpy as np


In [2]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype='int')
myarr1

array([100,   3,   1])

In [3]:
mylist2 = [1.2,3,True,'4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

In [4]:
mylist3 = [10,20,30,40,50]
myarr3 = np.array(mylist3)
print(type(myarr3),myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


In [5]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [7]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]


In [10]:
a= np.add(arr1, arr2)
print(a)
b= np.subtract(arr1, arr2)
print(b)
c= np.multiply(arr1, arr2)
print(c)
d= np.divide(arr1, arr2)
print(d)


[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]


In [13]:
grade = np.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [14]:
bool_array = np.array([True,False,True,False])
print(bool_array)


[ True False  True False]


In [15]:
result1 = grade[bool_array]
result1

array([82, 91])

In [16]:
mypoint = np.array([82,77,91,88])
ge80 = mypoint[mypoint>=80]
ge80

array([82, 91, 88])

In [18]:
ge80le90 = mypoint[np.logical_and(mypoint >=80, mypoint <=90)]
ge80le90

array([82, 88])

In [19]:
gt_or_lt = mypoint[np.logical_or(mypoint <80, mypoint >90)]
gt_or_lt

array([77, 91])

In [ ]:
exam = np.array([60,83,75,92,86])

#첫 번째 파라미터로 주어진 조건이 참일 경우 '합격'
#거짓일 경우 '불합격' 문자열을 반환
result = np.where(exam>=80, '합격','불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

In [21]:
exam = np.array([60,85,51,79,94,88])

conditions = [(exam >=90),
              (exam >=80),
              (exam>=70)]

value = ['A','B','C']

result = np.select(conditions, value, default='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')

In [25]:
score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

ndarray_score = np.array(score)
ndarray_score
print(ndarray_score[ndarray_score>=80.0])

[88.  91.5 80. ]


In [30]:
conditions = [(ndarray_score >=90),
              (ndarray_score >=80),
              (ndarray_score>=70)]
result = np.select(conditions, value, default='F')
print("원본 점수 :", ndarray_score)
print("80점 이상:", ndarray_score[ndarray_score>=80.0] )
result

원본 점수 : [72.5 88.  91.5 67.  80.  59.5]
80점 이상: [88.  91.5 80. ]


array(['C', 'B', 'A', 'F', 'B', 'F'], dtype='<U1')

2차원 배열 ndarray로 변환

In [2]:
import pandas as pd
import numpy as np

myarray = np.array([
    [98,72,80,64],
    [88,90,80,72],
    [92,88,82,76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수:", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


In [ ]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True,True,True,False]
])

# 조건에 맞는 항목만 1차 배열로 추출
# myarray는 이전 실습에서 생성한 2차원 배열
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])