# LAB 01 - NumPy Library [1]

## #02. `ndarray` 주요 기능

### 라이브러리 참조하기

In [1]:
import numpy as np


In [2]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype='int')
myarr1

array([100,   3,   1])

In [3]:
mylist2 = [1.2,3,True,'4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

In [4]:
mylist3 = [10,20,30,40,50]
myarr3 = np.array(mylist3)
print(type(myarr3),myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


In [5]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [7]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]


In [10]:
a= np.add(arr1, arr2)
print(a)
b= np.subtract(arr1, arr2)
print(b)
c= np.multiply(arr1, arr2)
print(c)
d= np.divide(arr1, arr2)
print(d)


[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]
[5. 5. 5. 5. 5.]


In [13]:
grade = np.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [14]:
bool_array = np.array([True,False,True,False])
print(bool_array)


[ True False  True False]


In [15]:
result1 = grade[bool_array]
result1

array([82, 91])

In [16]:
mypoint = np.array([82,77,91,88])
ge80 = mypoint[mypoint>=80]
ge80

array([82, 91, 88])

In [18]:
ge80le90 = mypoint[np.logical_and(mypoint >=80, mypoint <=90)]
ge80le90

array([82, 88])

In [19]:
gt_or_lt = mypoint[np.logical_or(mypoint <80, mypoint >90)]
gt_or_lt

array([77, 91])

In [ ]:
exam = np.array([60,83,75,92,86])

#첫 번째 파라미터로 주어진 조건이 참일 경우 '합격'
#거짓일 경우 '불합격' 문자열을 반환
result = np.where(exam>=80, '합격','불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

In [21]:
exam = np.array([60,85,51,79,94,88])

conditions = [(exam >=90),
              (exam >=80),
              (exam>=70)]

value = ['A','B','C']

result = np.select(conditions, value, default='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')

In [25]:
score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

ndarray_score = np.array(score)
ndarray_score
print(ndarray_score[ndarray_score>=80.0])

[88.  91.5 80. ]


In [30]:
conditions = [(ndarray_score >=90),
              (ndarray_score >=80),
              (ndarray_score>=70)]
result = np.select(conditions, value, default='F')
print("원본 점수 :", ndarray_score)
print("80점 이상:", ndarray_score[ndarray_score>=80.0] )
result

원본 점수 : [72.5 88.  91.5 67.  80.  59.5]
80점 이상: [88.  91.5 80. ]


array(['C', 'B', 'A', 'F', 'B', 'F'], dtype='<U1')

2차원 배열 ndarray로 변환

In [2]:
import pandas as pd
import numpy as np

myarray = np.array([
    [98,72,80,64],
    [88,90,80,72],
    [92,88,82,76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수:", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


In [ ]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True,True,True,False]
])

# 조건에 맞는 항목만 1차 배열로 추출
# myarray는 이전 실습에서 생성한 2차원 배열
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

In [4]:
result2 = myarray[myarray>=80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [5]:
result3 = myarray[np.logical_and(myarray>=80, myarray<=90)]
result3

array([80, 88, 90, 80, 88, 82])

In [6]:
result4 = myarray[np.logical_or(myarray<80, myarray>90)]
result4

array([98, 72, 64, 72, 92, 76])

In [7]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.full([3,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(10)

array([0.41837698, 0.16362991, 0.44468908, 0.56796083, 0.90582167,
       0.72277086, 0.81100761, 0.7358399 , 0.88935614, 0.51097283])

In [12]:
np.random.rand(4,3)

array([[0.62053227, 0.87066304, 0.64509189],
       [0.30604267, 0.15749013, 0.35338877],
       [0.86824897, 0.87679174, 0.0265939 ],
       [0.00761841, 0.00421795, 0.86705195]])

In [14]:
np.random.randint(0,9,10)

array([8, 8, 0, 3, 6, 3, 7, 4, 5, 2], dtype=int32)

In [15]:
np.random.randint(0,9,[3,4])

array([[4, 0, 0, 7],
       [3, 1, 5, 8],
       [6, 7, 8, 5]], dtype=int32)

In [16]:
np.random.seed(1234)
np.random.normal(0,1,(4,3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

In [17]:
np.random.randn(10)

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

In [18]:
np.random.randn(4,3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])