# LAB 01 - NumPy

## #04. 기초 통계량의 이해 (1)

### 라이브러리 참조

In [1]:
import numpy as np


### 샘플 데이터 생성

In [2]:
myarr= np.array([98,72,80,64,88,65,79,59,81,74])
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

In [3]:
print("총 도수:", len(myarr))

총 도수: 10


In [5]:
print("최대값:", np.max(myarr))
print("최소값:", np.min(myarr))
print("총합:", np.sum(myarr))

최대값: 98
최소값: 59
총합: 760


In [6]:
print("평균:", np.average(myarr))

평균: 76.0


In [7]:
size = len(myarr)
sorted_arr = np.sort(myarr)
print("정렬:", sorted_arr)

if size%2 ==0:
    p=(size//2)-1
    q= p+1
    median = (sorted_arr[p] + sorted_arr[q])/2
else:
    p = size//2
    median = sorted_arr[p]

print("중앙값:", median)

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


In [8]:
print("중앙값:", np.median(myarr))

중앙값: 76.5


In [9]:
x = np.sort(myarr)
n = len(x)
q1_pos = (n-1)*0.25
i = int(np.floor(q1_pos))
f = q1_pos - i

Q1 = x[i] + f * (x[i+1] - x[i])
print("직접 계산한 1사분위수 (Q1):", Q1)

print("Numpy로 계산한 1사분위수 (Q1):", np.quantile(myarr, 0.25))

직접 계산한 1사분위수 (Q1): 66.75
Numpy로 계산한 1사분위수 (Q1): 66.75


In [10]:
x = np.sort(myarr)
n = len(x)
q3_pos = (n-1)*0.75
i = int(np.floor(q3_pos))
f = q3_pos - i

Q3 = x[i] + f * (x[i+1] - x[i])
print("직접 계산한 3사분위수 (Q3):", Q3)

print("Numpy로 계산한 3사분위수:", np.quantile(myarr, 0.75))

직접 계산한 3사분위수 (Q3): 80.75
Numpy로 계산한 3사분위수: 80.75


In [13]:
import numpy as np
mydata = np.array([[1,2,3],[4,5,6]])
a=np.sum(mydata, axis=0)  # 열 방향 합계
b=np.sum(mydata, axis=1)  # 행 방향 합계
c=np.sum(mydata)         # 전체 합계
print("열 방향 합계:", a)
print("행 방향 합계:", b)
print("전체 합계:", c)

열 방향 합계: [5 7 9]
행 방향 합계: [ 6 15]
전체 합계: 21


In [ ]:
# mean은 평균값 계산
alpha = [88,92,76,100,95]
np.mean(alpha)
# median은 중앙값 계산
np.median(alpha)
# std는 표준편차 계산
np.std(alpha)
# var는 분산 계산
np.var(alpha)
# sum은 합계 계산
np.sum(alpha)
# min은 최소값 계산
np.min(alpha)
# max는 최대값 계산
np.max(alpha)
# quantile은 분위수 계산
np.quantile(alpha, 0.25)  # 1사분위수
np.quantile(alpha, 0.75)  # 3사분위수
# argmin은 최소값의 인덱스 반환
np.argmin(alpha)
# argmax는 최대값의 인덱스 반환
np.argmax(alpha)

np.float64(90.2)

In [ ]:
# 히스토그램 계산
data=   [5,15,25,35,45,20,10,30,40,50]
# bins는 구간 설정, 마지막 30은 포함되지 않음
np.histogram(data,bins=[0,10,20,30])

(array([1, 2, 3]), array([ 0, 10, 20, 30]))

In [17]:
# 평균이 중앙값보다 작다는 것은 왼쪽으로 꼬리가 긴 분포를 의미
# 왜?
# 극단적으로 작은 값들이 평균을 끌어내리기 때문
# 반대로 평균이 중앙값보다 크다는 것은 오른쪽으로 꼬리가 긴 분포를 의미
# 왜?
# 극단적으로 큰 값들이 평균을 끌어올리기 때문
# 누적 도수 배열의 마지막 값은 전체 도수와 같다
# 마지막 값이 전체 도수이자 가장 큰 도수이므로 히스토그램의 최댓값이 된다
# 누적도수 배열의 마지막 값은 전체 데이터 개수와 같다


In [ ]:
sales_data = [18,25,33,21,28,40,15,3,9,17,22,29,38,45,11,6,31,24,27,35,12,19,39,42,7,2,20,34,26,30]
numpy_sales = np.array(sales_data)
hist, bin= np.histogram(numpy_sales, bins = [0,10,20,30,40,50])
print(hist)
print(bin)
#판매량이 20미만인 날들의 누적도수
cum_hist = np.cumsum(hist)
print(cum_hist)
#각 구간의 실제 빈도수를 무엇이라 하냐?
#빈도수(frequency)라고 한다
#bins = [0,10,20,30] 일 때 첫 번째 구간은 일반적으로 0 이상 10 미만을 의미
# 마지막 구간은 일반적으로 40 이상 50 미만을 의미

[5 6 9 7 3]
[ 0 10 20 30 40 50]
[ 5 11 20 27 30]
