# [LAB-02] Pandas

## #01. Series 자료형
 
### 라이브러리 참조

In [1]:
import numpy as np
from pandas import Series

In [2]:
my_list = [10,30]
s1 = Series(my_list)
s1

0    10
1    30
dtype: int64

In [3]:
my_array = np.array([100,200])
s2 = Series(my_array)
s2

0    100
1    200
dtype: int64

In [4]:
my_dict = {"hello": 123, "world": 456, "nice": 789}
s3 = Series(my_dict)
s3

hello    123
world    456
nice     789
dtype: int64

In [5]:
my_series=Series({"hello": 123, "world":456,"nice":789})
my_series.dtype

dtype('int64')

In [6]:
my_series.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, hello to nice
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0+ bytes


In [8]:
my_series = Series([10,20,30,40,50])
print("== 인덱싱 ==")
print(my_series[0])
print("== 슬라이싱 ==")
print(my_series[1:3])

== 인덱싱 ==
10
== 슬라이싱 ==
1    20
2    30
dtype: int64


In [9]:
my_series = Series({"a":100,"b":200,"c":300,"d":400})
print("== 인덱싱 ==")
print(my_series["a"])
print("== 슬라이싱 ==")
print(my_series["b":"d"])

== 인덱싱 ==
100
== 슬라이싱 ==
b    200
c    300
d    400
dtype: int64


In [10]:
my_series = Series({"a":100, "b": 200, "c":300,"d":400})

print(type(my_series.values))
my_series.values

<class 'numpy.ndarray'>


array([100, 200, 300, 400])

In [11]:
mylist = list(my_series.values)
mylist

[np.int64(100), np.int64(200), np.int64(300), np.int64(400)]

In [12]:
my_series = Series({"a":100, "b": 200,"c": 300,"d": 400})
print(type(my_series.index))
my_series.index

<class 'pandas.core.indexes.base.Index'>


Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
mylist = list(my_series.index)
mylist

['a', 'b', 'c', 'd']

In [4]:
import numpy as np
from pandas import Series
s=Series([1,2,6])
s.sum()

np.int64(9)

In [5]:
s = Series([10,20,np.nan,40])
s.sum()  # NaN은 무시하고 합계 계산

np.float64(70.0)

In [6]:
s=Series([10,20,30,40,50])
s.quantile(0.5)

np.float64(30.0)

In [10]:
s.values

array([10, 20, 30, 40, 50])

In [11]:
s[1]

np.int64(20)

In [17]:
#s.index의 반환값 데이터 타입
type(s.index)

pandas.core.indexes.range.RangeIndex

In [18]:
#시리즈의 최빈값
s=Series([1,2,2,3,3,3,4,4,4,4])
s.mode()  # 최빈값 반환

0    4
dtype: int64

In [19]:
# 시리즈에서 값만 추출하여 numpy배열로 얻기 위한 속성
s.values

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

In [21]:
my_dict = {"a":1, "b":2}
s = Series(my_dict)
s

a    1
b    2
dtype: int64

In [ ]:
s=Series([1,2,3,100])
# 이때 평균과 중앙값 중 중심 경향을 더 잘나타내는것은
s.median()
# 왜 ?
# 평균은 극단값(이경우 100)에 영향을 많이 받기 때문

np.float64(2.5)

In [24]:
s1 = Series({"a":10, "b":20, "c":30})
s2 = Series({"b":200, "c":300, "d":400})
s1+s2

a      NaN
b    220.0
c    330.0
d      NaN
dtype: float64

In [ ]:
#series에서 여러 조건을 and 관계로 결합하여 사용하는 기호
# &